import type { PaginationState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: PaginationState, fileName = "pagination") : ExportPayload {
  return { fileName: `${fileName || "pagination"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: PaginationState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
    "",
    "function clampPage() {",
    "  return Math.min(Math.max(state.currentPage, 1), Math.max(state.pageCount, 1));",
    "}",
    "",
    "function pageRange(start, end) {",
    "  return Array.from({ length: Math.max(end - start + 1, 0) }, (_, index) => start + index);",
    "}",
    "",
    "function visiblePages() {",
    "  const total = Math.max(state.pageCount, 1);",
    "  const current = clampPage();",
    "  const boundary = Math.max(state.boundaryCount, 0);",
    "  const siblings = Math.max(state.siblingCount, 0);",
    "  const fullWindow = boundary * 2 + siblings * 2 + 3;",
    "  if (total <= fullWindow) return pageRange(1, total);",
    "  const pages = new Set();",
    "  pageRange(1, boundary).forEach((page) => pages.add(page));",
    "  pageRange(total - boundary + 1, total).forEach((page) => pages.add(page));",
    "  pageRange(current - siblings, current + siblings).forEach((page) => {",
    "    if (page >= 1 && page <= total) pages.add(page);",
    "  });",
    "  const sorted = Array.from(pages).sort((a, b) => a - b);",
    "  return sorted.flatMap((page, index) => {",
    "    const previous = sorted[index - 1];",
    "    if (!previous || page - previous === 1) return [page];",
    "    return [page - previous === 2 ? previous + 1 : index === 1 ? \"ellipsis-left\" : \"ellipsis-right\", page];",
    "  });",
    "}",
    "",
    "export default function PaginationComponent() {",
    "  const currentPage = clampPage();",
    "  const totalPages = Math.max(state.pageCount, 1);",
    "  const isPreviousDisabled = state.disabled || currentPage <= 1;",
    "  const isNextDisabled = state.disabled || currentPage >= totalPages;",
    "  const panel = { width: state.width, minHeight: state.height, padding: state.padding, borderRadius: state.radius, border: state.borderWidth + \"px solid \" + state.border, boxShadow: \"0 \" + Math.round(state.shadow / 3) + \"px \" + state.shadow + \"px rgba(0,0,0,.28)\", background: state.background, color: state.foreground, fontFamily: state.fontFamily, opacity: state.disabled ? 0.6 : 1 };",
    "  const buttonStyle = (selected = false, disabled = false) => ({ minWidth: 40, height: 40, padding: \"0 12px\", borderRadius: Math.max(state.radius - 8, 8), border: state.borderWidth + \"px solid \" + (selected ? state.accent : state.border), background: selected ? state.accent : \"transparent\", color: selected ? state.background : state.foreground, fontWeight: selected ? 800 : state.fontWeight, opacity: disabled ? 0.45 : 1, transition: state.motion ? \"background 0.2s ease, color 0.2s ease, border-color 0.2s ease, opacity 0.2s ease\" : \"none\" });",
    "  return (",
    "    <nav id={state.id} aria-label={state.ariaLabel} tabIndex={state.tabIndex} style={panel} data-component=\"pagination\" data-preview-state={state.previewState}>",
    "      <h3 style={{ fontSize: state.titleSize, fontWeight: state.fontWeight }}>{state.title}</h3>",
    "      <p style={{ color: state.muted, fontSize: state.bodySize }}>{state.description}</p>",
    "      <div style={{ display: \"flex\", flexWrap: \"wrap\", alignItems: \"center\", gap: state.gap, marginTop: 20 }} aria-label={`${state.label}: page ${currentPage} of ${totalPages}`}>",
    "        {state.showFirstLast && <button type=\"button\" aria-label=\"Go to first page\" disabled={isPreviousDisabled} style={buttonStyle(false, isPreviousDisabled)}>First</button>}",
    "        {state.showPrevNext && <button type=\"button\" aria-label=\"Go to previous page\" disabled={isPreviousDisabled} style={buttonStyle(false, isPreviousDisabled)}>Previous</button>}",
    "        {visiblePages().map((page) => typeof page === \"number\" ? (",
    "          <button key={page} type=\"button\" aria-label={`Go to page ${page}`} aria-current={page === currentPage ? \"page\" : undefined} disabled={state.disabled} style={buttonStyle(page === currentPage, state.disabled)}>{page}</button>",
    "        ) : (",
    "          <span key={page} aria-hidden=\"true\" style={{ color: state.muted }}>...</span>",
    "        ))}",
    "        {state.showPrevNext && <button type=\"button\" aria-label=\"Go to next page\" disabled={isNextDisabled} style={buttonStyle(false, isNextDisabled)}>Next</button>}",
    "        {state.showFirstLast && <button type=\"button\" aria-label=\"Go to last page\" disabled={isNextDisabled} style={buttonStyle(false, isNextDisabled)}>Last</button>}",
    "      </div>",
    "      <p style={{ color: state.muted, fontSize: 12, marginTop: 16 }}>{state.helper} Page {currentPage} of {totalPages}.</p>",
    "    </nav>",
    "  );",
    "}",
    "",
  ].join("\n");
}
